### ISSUE TITLE
Bash script failing on Windows and apparent indexing issues with 0_normalize1.py

### ISSUE THREAD

**Issue by cmkuo12** [interaction-lab/BTFromSARDemostration#21]
I'm finding these issues when running the scripts with Windows Command Prompt.

![Screenshot 2021-01-08 031629](https://user-images.githubusercontent.com/54866570/104052830-21951380-519f-11eb-8d9e-15393b7c8dcb.png)

Running `sh clean_script.sh config.json` results in the above error.

![Screenshot 2021-01-08 105055](https://user-images.githubusercontent.com/54866570/104053081-818bba00-519f-11eb-8f34-08e13dc1f02b.png)

Running `python3 0_normalize1.py -config config.json` results in some indexing error.

**Comment by tgroechel** [comment]
I can't seem to reproduce; could you try removing the whole repo and reclone @cmkuo12 ? I added new install instructions into the `README.md`

**Comment by tgroechel** [comment]
@cmkuo12 close if no longer needed
